version: '3'
services:
  applicationmftf:
    build: docker-files/apache-php72
    ports:
      - "80:80"
    volumes:
      - './../magento:/var/www/html:delegated'
    expose:
      - "9001"
    networks:
      tests:
        aliases:
          - magento2.mftf

  seleniumchromemftf:
    image: magestore/mftf-selenium-chrome
    ports:
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
    environment:
      START_XVFB: "false"
    networks:
      - tests

  alluremftf:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1
    ports:
      - "4040:4040"
      - "5050:5050"
    volumes:
      - './../magento/dev/tests/_output/allure-results:/app/allure-results:delegated'
    networks:
      - tests

networks:
  tests:
